language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
before_install:
- set -e
- export CXX="g++-5"
install:
- npm install
script:
- npm test
after_success:
- fly deploy
env:
  global:
    secure: "Q8ouzxuGIH3ONlgr3IeT5fcnUWod7LWz7MX7Il+yDWYYZcYd3YpsYUB3lZuyWNuaQi2q5FC3YfLQ/gZfgn5PvMd4CquZjocbZVa8pnhVyPWGvm3lid6VEWt9zM5bEXXFjxzSn9V/wkU5Agqo7clraYdSaOnHdCjFML0DY4VKj0BRw7i5fhY6w4XU6S37ID1qn8XATscmo7BvZdKwx6DJ/Cl3yehNDcrdl7AsilOixZdTRpZ7eL+t6TR0iIV5f8+O11AaVdVkNgtzX29MdJMM4AjJDk2Vn4MrVgsBvbljvEMMbi0rZeqYUHRrvqeiKnZl6sGjfSzm0dumzciKhO0UglmbhNdfsVHeo4IfZ4PZDGn6T67RYdNSDBfI1SuMXmjUdShW9XlOe8su6+y4m1d5soz2CXKqMKcusc9vR05JC2iUh15DzETQ1Sh5QCi0gLRS4gHh9qjcvwkxF+pZbyUvEmghX8KNjNXveXj1UlWRxZF/u7s7jVsPy4JNhm/rq3Ylu6nrCom68qtz+WYfXhhQGvOSnQj9gy9Nkdq6pwqjmrCQ37W8AT4NraMnadxIQA9LaDmkvJNXUnQDy+KQhm+fNpM7Fzsn6qxzUgVYz5PCL36MTZME8yaxAc54y/LhRyVwebRjKEqOnk54+9f1efM/V2w2buZ89kWP0oTNuNFaSnU="

